FEED_RATE = 2000
TRAVEL_RATE = 5000
PEN_UP_COMMAND = "M3 S80"
PEN_DOWN_COMMAND = "M5 S10"
UNITS = "mm"

# Version 2.0 settings
PLOTTER_WIDTH = 200.0
PLOTTER_HEIGHT = 200.0
AUTO_SCALE = False
AUTO_CENTER = False
SMOOTHING_ITERATIONS = 0
PRESERVE_ASPECT = True
